// <auto-generated />
namespace AcunmedyaAkademiProject2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mg_admin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg_admin));
        
        string IMigrationMetadata.Id
        {
            get { return "202502261306586_mg_admin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
