// <auto-generated />
namespace AcunmedyaAkademiProject2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mg_contact1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg_contact1));
        
        string IMigrationMetadata.Id
        {
            get { return "202502201556025_mg_contact1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
